using UnityEngine;
using UnityEditor;

// Generated by HandPoseSetting.cs ver 1.1
// © 2018-9-25 gatosyocora

public class CustomHandPoseAdder : EditorWindow {
  [MenuItem("CONTEXT/Motion/Add Hand pose 'NoBlink'", false, 8)]
  private static void AddFPAnimationKeys(MenuCommand command) {
      string animClipPath = "Assets/Karpo/Liqu/Animation/NoBlink.anim";
      HandPoseAdder.AddHandPoseAnimationKeys(command, animClipPath);
  }
}
